### ISSUE TITLE
README

### ISSUE THREAD

**Issue by taylortrimble** [mplewis/sternidae-ios#1]
Can a little birdy tell me what this project is about?

**Comment by mplewis** [comment]
Yep! It's a (motor|bi)cycle nav system. I want to know how to get to my destination without being told how to get there. Was going to build this in [Arduino](https://github.com/mplewis/sternidae) for the motorcycle, but turns out phones have pretty awesome hardware and I don't have to spin a PCB. Inspired by the awesome [dwaler](https://github.com/vespakoen/dwaler) project.

I'll keep this open until the project gets a README. Pic of the app (I'm traveling south):

<img src="https://cloud.githubusercontent.com/assets/1829094/18726132/442ed504-8000-11e6-8810-439bc1e281c5.PNG" width="200px">

**Comment by taylortrimble** [comment]
Whoa, that is a cool project. Good luck!
